username: "<USERNAME>"
password: "<PASSWORD>"
email: "<EMAIL>"

namespace: "wso2"
svcaccount: "wso2svc-account"
serverIp: "<SERVER_IP>"
sharedDeploymentLocationPath: "<NFS_LOCATION>"
sharedTenantsLocationPath: "<NFS_LOCATION>"
analytics1DataLocationPath: "<NFS_LOCATION>"
analytics2DataLocationPath: "<NFS_LOCATION>"
brokerSharedDeploymentLocationPath: "<NFS_LOCATION>"
analytics1LocationPath: "<NFS_LOCATION>"
analytics2LocationPath: "<NFS_LOCATION>"
