# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-analytics-worker-deployment-2
  namespace : {{ .Release.Namespace }}
spec:
  replicas: {{ default 1 .Values.wso2.deployment.wso2eiAnalyticsWorker2.replicas }}
  minReadySeconds: {{ default 75 .Values.wso2.deployment.wso2eiAnalyticsWorker2.minReadySeconds }}
  strategy:
    rollingUpdate:
      maxSurge: {{ default 1 .Values.wso2.deployment.wso2eiAnalyticsWorker2.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ default 0 .Values.wso2.deployment.wso2eiAnalyticsWorker2.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: {{ template "fullname" . }}-analytics-worker-2
      app: {{ template "fullname" . }}
      monitoring: {{ default "jmx" .Values.wso2.monitoring.prometheus.jmxJobName }}
  template:
    metadata:
      labels:
        deployment: {{ template "fullname" . }}-analytics-worker-2
        app: {{ template "fullname" . }}
        monitoring: {{ default "jmx" .Values.wso2.monitoring.prometheus.jmxJobName }}
    spec:
      initContainers:
      {{ if .Values.wso2.monitoring.enabled }}
      - name: init-jmx-exporter
        image: busybox:1.31
        command:
          - /bin/sh
          - "-c"
          - |
            set -e
            wget https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar -P /jmx-jar/
        volumeMounts:
          - name: shared-prometheus-jmx-jar
            mountPath: /jmx-jar
      {{ end }}
      {{ if .Values.wso2.mysql.enabled }}
      - name: init-ei-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z {{ default "wso2ei-rdbms-service-mysql" .Values.wso2.mysql.host }} 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
      {{ end }}
      {{ if .Values.wso2.centralizedLogging.enabled }}
      - name: init-logstash-plugins-install
        image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
        command:
          - /bin/sh
          - "-c"
          - |
            set -e
            ./bin/logstash-plugin install logstash-codec-multiline logstash-filter-grok
        volumeMounts:
          - name: shared-plugins
            mountPath: /usr/share/logstash/plugins/
      - name: init-elasticsearch
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of Elasticsearch Server deployment"; while ! nc -z {{ default "wso2-elasticsearch-master" .Values.wso2.centralizedLogging.logstash.elasticsearch.host }} 9200; do sleep 1; printf "-"; done; echo -e "  >> Elasticsearch server has started";']
      {{ end }}
      containers:
      - name: wso2ei-analytics-worker
        {{ if .Values.wso2.deployment.wso2eiAnalyticsWorker2.dockerRegistry }}
        image: {{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.dockerRegistry }}/{{ default "wso2ei-analytics-worker" .Values.wso2.deployment.wso2eiAnalyticsWorker2.imageName }}
        {{- $tag := .Values.wso2.deployment.wso2eiAnalyticsWorker2.imageTag }}
        {{- if not (eq $tag "") }}{{- printf ":%s" $tag -}}{{- end }}
        {{ else if or (eq .Values.wso2.subscription.username "") (eq .Values.wso2.subscription.password "") }}
        image: wso2/{{ default "wso2ei-analytics-worker" .Values.wso2.deployment.wso2eiAnalyticsWorker2.imageName }}:{{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.imageTag }}
        {{ else }}
        image: docker.wso2.com/{{ default "wso2ei-analytics-worker" .Values.wso2.deployment.wso2eiAnalyticsWorker2.imageName }}:{{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.imageTag }}
        {{ end }}
        env:
        -
          name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            memory: {{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.resources.limits.memory }}
            cpu: {{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.resources.limits.cpu }}
          requests:
            memory: {{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.resources.requests.memory }}
            cpu: {{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.resources.requests.cpu }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nc -z localhost 9444
          initialDelaySeconds: {{ default 20 .Values.wso2.deployment.wso2eiAnalyticsWorker2.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 10 .Values.wso2.deployment.wso2eiAnalyticsWorker2.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 9444
          initialDelaySeconds: {{ default 20 .Values.wso2.deployment.wso2eiAnalyticsWorker2.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 10 .Values.wso2.deployment.wso2eiAnalyticsWorker2.readinessProbe.periodSeconds }}
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/analytics-worker.sh stop']
        imagePullPolicy: Always
        securityContext:
          runAsUser: 802
        ports:
          {{- if .Values.wso2.monitoring.enabled }}
          - containerPort: 2222
            protocol: TCP
            name: metrics
          {{ end }}
          -
            containerPort: 9444
            protocol: TCP
          -
            containerPort: 9091
            protocol: TCP
          -
            containerPort: 9711
            protocol: TCP
          -
            containerPort: 9611
            protocol: TCP
          -
            containerPort: 7712
            protocol: TCP
          -
            containerPort: 7612
            protocol: TCP
          -
            containerPort: 7070
            protocol: TCP
          -
            containerPort: 7443
            protocol: TCP
          -
            containerPort: 9894
            protocol: TCP
        volumeMounts:
        - name: analytics-conf-worker
          mountPath: /home/wso2carbon/wso2-config-volume/wso2/analytics/conf/worker
        {{ if .Values.wso2.monitoring.enabled }}
        - name: shared-prometheus-jmx-jar
          mountPath: /home/wso2carbon/prometheus
        - name: integrator-prometheus-exporter-conf
          mountPath: /home/wso2carbon/prometheus/config.yaml
          subPath: config.yaml
        - name: analytics-worker-bin
          mountPath: /home/wso2carbon/wso2-config-volume/wso2/analytics/wso2/worker/bin
        {{ end }}
      {{ if .Values.wso2.centralizedLogging.enabled }}
        - name: shared-logs
          mountPath: /home/wso2carbon/wso2ei-6.5.0/wso2/analytics/wso2/worker/logs
      - name: wso2ei-logstash
        image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
        livenessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: {{ default 90 .Values.wso2.centralizedLogging.logstash.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 30 .Values.wso2.centralizedLogging.logstash.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: {{ default 90 .Values.wso2.centralizedLogging.logstash.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 30 .Values.wso2.centralizedLogging.logstash.readinessProbe.periodSeconds }}
        volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/logstash/wso2-logs/
          - name: logstash-yml
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: c5-logstash-conf
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
          - name: shared-plugins
            mountPath: /usr/share/logstash/plugins/
        env:
          - name: NODE_ID
            value: {{ .Release.Name }}-analytics-worker-node-2
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: logstash-elasticsearch-creds
                key: username
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: logstash-elasticsearch-creds
                key: password
          - name: ELASTICSEARCH_HOST
            value: {{ default "wso2-elasticsearch-master" .Values.wso2.centralizedLogging.logstash.elasticsearch.host }}
      {{ end }}
      serviceAccountName: {{ .Values.kubernetes.svcaccount }}
      {{- if .Values.wso2.deployment.wso2eiAnalyticsWorker2.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.wso2.deployment.wso2eiAnalyticsWorker2.imagePullSecrets }}
      {{- else if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
      - name: wso2ei-deployment-creds
      {{ end }}
      volumes:
      - name: analytics-conf-worker
        configMap:
          name: analytics-conf-worker
      {{ if .Values.wso2.centralizedLogging.enabled }}
      - name: shared-logs
        emptyDir: {}
      - name: logstash-yml
        configMap:
          name: logstash-yml
      - name: c5-logstash-conf
        configMap:
          name: c5-logstash-conf
      - name: shared-plugins
        emptyDir: {}
      - name: logstash-elasticsearch-creds
        secret:
          secretName: logstash-elasticsearch-creds
      {{ end }}
      {{ if .Values.wso2.monitoring.enabled }}
      - name: shared-prometheus-jmx-jar
        emptyDir: {}
      - name: integrator-prometheus-exporter-conf
        configMap:
          name: integrator-prometheus-exporter-conf
      - name: analytics-worker-bin
        configMap:
          name: analytics-worker-bin
      {{ end }}
