# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wso2ei-scalable-integrator-deployment
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2ei-scalable-integrator
    spec:
      containers:
      - name: wso2ei-scalable-integrator
        image: docker.wso2.com/wso2ei-integrator:6.3.0
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 9443
          initialDelaySeconds: 100
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - nc -z localhost 9443
          initialDelaySeconds: 100
          periodSeconds: 10
        imagePullPolicy: Always
        ports:
        - containerPort: 8280
          protocol: TCP
        - containerPort: 8243
          protocol: TCP
        - containerPort: 9763
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: integrator-conf
          mountPath: /home/wso2carbon/kubernetes-volumes/integrator/conf
        - name: integrator-conf-axis2
          mountPath: /home/wso2carbon/kubernetes-volumes/integrator/conf-axis2
        - name: integrator-conf-datasources
          mountPath: /home/wso2carbon/kubernetes-volumes/integrator/conf-datasources
        - name: shared-pd
          mountPath: /home/wso2carbon/wso2ei-6.3.0/repository/deployment/server
      serviceAccountName: "wso2svc-account"
      imagePullSecrets:
      - name: wso2creds
      volumes:
      - name: integrator-conf
        configMap:
          name: integrator-conf
      - name: integrator-conf-axis2
        configMap:
          name: integrator-conf-axis2
      - name: integrator-conf-datasources
        configMap:
          name: integrator-conf-datasources
      - name: shared-pd
        persistentVolumeClaim:
          claimName: scalable-integrator-shared-volume-claim
