
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2ei-with-analytics-worker-deployment
  namespace: "$ns.k8s&wso2.ei"
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2ei-with-analytics-worker
      node: wso2ei-with-analytics-worker
      product: wso2ei
  template:
    metadata:
      labels:
        deployment: wso2ei-with-analytics-worker
        node: wso2ei-with-analytics-worker
        product: wso2ei
    spec:
      containers:
        - name: wso2ei-with-analytics-worker
          image: "$image.pull.@.wso2"/wso2ei-analytics-worker:6.6.0
          env:
            -
              name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9444
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 7712
            initialDelaySeconds: 10
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/analytics-worker.sh stop']
          imagePullPolicy: Always
          securityContext:
            runAsUser: 802
          ports:
            -
              containerPort: 9444
              protocol: TCP
            -
              containerPort: 9091
              protocol: TCP
            -
              containerPort: 9711
              protocol: TCP
            -
              containerPort: 9611
              protocol: TCP
            -
              containerPort: 7712
              protocol: TCP
            -
              containerPort: 7612
              protocol: TCP
            -
              containerPort: 7070
              protocol: TCP
            -
              containerPort: 7443
              protocol: TCP
            -
              containerPort: 9894
              protocol: TCP
          volumeMounts:
            - name: ei-analytics-conf-worker
              mountPath: /home/wso2carbon/wso2-config-volume/wso2/analytics/conf/worker
      initContainers:
        - name: init-ei-with-analytics
          image: busybox
          command: ['sh', '-c', 'echo -e "checking for the availability of MySQL"; while ! nc -z wso2ei-integrator-with-analytics-rdbms-service 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL server started";']
      serviceAccountName: "wso2svc-account"
      imagePullSecrets:
        - name: wso2creds
      volumes:
        - name: ei-analytics-conf-worker
          configMap:
            name: ei-analytics-conf-worker
---
